import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";



const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased `}
        style={{backgroundImage: `url(https://res.cloudinary.com/seunsanyaa/image/upload/v1766821097/Container_2_hz9hq7.png)`, backgroundSize: 'cover', backgroundPosition: 'center', backgroundRepeat: 'no-repeat'}}
      >
        {children}
      </body>
    </html>
  );
}
